runtime: java17  
env: standard

instance_class: F1 
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 2

handlers:
  - url: /.*
    script: auto
